# Generated by Django 6.0.7 on 2026-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_employeedocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='action_type',
            field=models.CharField(choices=[('UPLOAD', 'Requires Upload'), ('SIGNATURE', 'Requires Signature'), ('VIEW_ONLY', 'View Only')], default='UPLOAD', max_length=20),
        ),
    ]
