# Generated by Django 6.0.7 on 2026-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
