# Generated by Django 6.0.7 on 2026-07-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_employeedocument_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
